### ISSUE TITLE
Ground cover resampling code is incomplete

### ISSUE THREAD

**Issue by bglarkin** [bglarkin/efficient_intercepts#1]
# Complete the ground cover resampling code
- The code linked here is a good start, but needs to be modified and finished to continue the analysis
- **This is a test** as I have not done an issue or branch yet

## Tasks
- [x] create branch
- [x] develop code to address the issue
- [ ] pull request
- [ ] merge branch to main
- [ ] close the issue

https://github.com/bglarkin/efficient_intercepts/blob/0e8592a76446a3904537564c61d1303211d939de/raw_code_sandbox.R#L268-L281
